version: '2.1'

services:

  lampman:
    container_name: lampman-proj-lampman
    image: kazaoki/lampman
    ports:
      - "80:80"
      - "443:443"
      - "9981:9981"
    volumes:
      - ./:/lampman
      - ../public_html:/var/www/html
    entrypoint: /lampman/lampman/entrypoint.sh
    labels:
      - "kazaoki-lampman"
    environment:
      LAMPMAN_MAILDEV_START: 1
      LAMPMAN_MAILDEV_PORT: 9981
