version: '2.1'

services:

  mysql:
    container_name: lampman-test-mysql
    # restart: always
    image: mysql:5.7
    # ports:
    #   - "3306:3306"
    volumes:
      - ./mysql:/mysql
      - mysql_data:/var/lib/mysql
    entrypoint: /mysql/before-entrypoint.sh
    command: ["mysqld"]
    labels:
      - "kazaoki-lampman"
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      DUMP_ROTATIONS: 3
      IS_LOCKED: 0
    networks:
      - lampman-test-internals

  mysql_2:
    container_name: lampman-test-mysql_2
    # restart: always
    image: mysql:5.7
    # ports:
    #   - "3307:3306"
    volumes:
      - ./mysql_2:/mysql
      - mysql_2_data:/var/lib/mysql
    entrypoint: /mysql/before-entrypoint.sh
    command: ["mysqld"]
    labels:
      - "kazaoki-lampman"
    environment:
      MYSQL_ROOT_PASSWORD: test2
      MYSQL_DATABASE: test2
      MYSQL_USER: test2
      MYSQL_PASSWORD: test2
      DUMP_ROTATIONS: 3
      IS_LOCKED: 0
    networks:
      - lampman-test-internals

  postgresql:
    container_name: lampman-test-postgresql
    # restart: always
    # image: postgres:9
    image: kazaoki/postgres-bigm
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/postgresql
      - postgresql_data:/var/lib/postgresql/data
    entrypoint: /postgresql/before-entrypoint.sh
    command: ["postgres"]
    labels:
      - "kazaoki-lampman"
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: test
    networks:
      - lampman-test-internals

  phpenv:
    container_name: lampman-test-phpenv
    image: kazaoki/phpenv:5.6.22
    labels:
      - "kazaoki-lampman"

  lampman:
    container_name: lampman-test-lampman
    # restart: always
    # depends_on:
    #   - phpenv
    #   - mysql
    #   - mysql_2
    #   - postgresql
    image: kazaoki/lampman
    ports:
      - "80:80"
      - "443:443"
      - "9981:9981"
    volumes:
      - ./:/lampman
      - ../public_html:/var/www/html
    volumes_from:
      - phpenv
    entrypoint: /lampman/lampman/entrypoint.sh
    labels:
      - "kazaoki-lampman"
    environment:
      LAMPMAN_PHP_PHPENV_IMAGE: kazaoki/phpenv:5.6.22
      LAMPMAN_PHP_PHPENV_VERSION: 5.6.22
      LAMPMAN_PHP_ERROR_REPORT: 1
      LAMPMAN_PHP_XDEBUG_START: 1
      LAMPMAN_PHP_XDEBUG_HOST: 192.168.0.10
      LAMPMAN_PHP_XDEBUG_PORT: 9000
      LAMPMAN_BIND_HOSTS: main.db:mysql, main-2.db:mysql_2, sub.db:postgresql
      LAMPMAN_MAILDEV_START: 1
      LAMPMAN_MAILDEV_PORT: 9981
      LAMPMAN_MYSQLS: mysql, mysql_2
      LAMPMAN_POSTGRESQLS: postgresql
    networks:
      - lampman-test-internals

volumes:
  mysql_data:
    driver: local
    name: lampman-test-mysql_data
  mysql_2_data:
    driver: local
    name: lampman-test-mysql_2_data
  postgresql_data:
    driver: local
    name: lampman-test-postgresql_data

# 以下、必要なのか要検証
networks:
  lampman-test-internals:
    driver: bridge
